import Head from 'next/head';
import axios from 'axios';
import { useState, useEffect } from 'react';
import styles from '../styles/Home.module.css';

export default function Home() {
	const [posts, setPosts] = useState([]);

	const fetchPosts = async () => {
		const { data } = await axios.get(`/api/posts`);
		setPosts(data);
	};

	useEffect(() => {
		fetchPosts();
	}, []);

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1>NextJs Security Optimization</h1>
				<br />
				<h1>This is the API called with CORS in API Routes</h1>
				{posts?.map((post) => (
					<div key={post.id}>
						<h2>{post.title}</h2>
						<p>{post.body}</p>
					</div>
				))}
			</main>
		</div>
	);
}

// export const getStaticProps = async () => {
// 	const { data } = await axios.get(
// 		'https://jsonplaceholder.typicode.com/posts'
// 	);
// 	const subData = data.slice(0, 10);
// 	return {
// 		props: { subData }
// 	};
// };
